"""Create events model

Revision ID: ab63083cbcad
Revises: c7a5f1960770
Create Date: 2021-04-14 16:19:04.044887

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ab63083cbcad'
down_revision = 'c7a5f1960770'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('participants', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('raid_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['raid_id'], ['raids.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###
