"""Create boss model

Revision ID: dc3cdba1fb01
Revises: a722f4641124
Create Date: 2021-04-14 14:23:12.464681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc3cdba1fb01'
down_revision = 'a722f4641124'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bosses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('url_img', sa.String(length=200), nullable=True),
    sa.Column('min_cp_range', sa.Integer(), nullable=False),
    sa.Column('max_cp_range', sa.Integer(), nullable=False),
    sa.Column('boosted_min_cp_range', sa.Integer(), nullable=False),
    sa.Column('boosted_max_cp_range', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('url_img')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bosses')
    # ### end Alembic commands ###
