"""Edit users model

Revision ID: dd23de01f62a
Revises: 2d1cd4daf33d
Create Date: 2021-04-14 17:08:41.941481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd23de01f62a'
down_revision = '2d1cd4daf33d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('team_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'team_id')
    # ### end Alembic commands ###
