"""Update raids model, drop bosses model

Revision ID: da6d168caf67
Revises: dd23de01f62a
Create Date: 2021-04-15 19:04:59.733861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da6d168caf67'
down_revision = 'dd23de01f62a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raid_pokemon_types',
    sa.Column('raid_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['raid_id'], ['raids.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['types.id'], ),
    sa.PrimaryKeyConstraint('raid_id', 'type_id')
    )
    op.add_column('raids', sa.Column('boosted_max_cp_range', sa.Integer(), nullable=False))
    op.add_column('raids', sa.Column('boosted_min_cp_range', sa.Integer(), nullable=False))
    op.add_column('raids', sa.Column('max_cp_range', sa.Integer(), nullable=False))
    op.add_column('raids', sa.Column('min_cp_range', sa.Integer(), nullable=False))
    op.add_column('raids', sa.Column('pokemon', sa.String(length=50), nullable=False))
    op.add_column('raids', sa.Column('url_img', sa.String(length=200), nullable=True))
    op.alter_column('raids', 'gym_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'raids', ['pokemon'])
    op.create_unique_constraint(None, 'raids', ['url_img'])
    op.drop_constraint('raids_boss_id_fkey', 'raids', type_='foreignkey')
    op.drop_column('raids', 'boss_id')
    op.drop_table('boss_types')
    op.drop_table('bosses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raids', sa.Column('boss_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('raids_boss_id_fkey', 'raids', 'bosses', ['boss_id'], ['id'])
    op.drop_constraint(None, 'raids', type_='unique')
    op.drop_constraint(None, 'raids', type_='unique')
    op.alter_column('raids', 'gym_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('raids', 'url_img')
    op.drop_column('raids', 'pokemon')
    op.drop_column('raids', 'min_cp_range')
    op.drop_column('raids', 'max_cp_range')
    op.drop_column('raids', 'boosted_min_cp_range')
    op.drop_column('raids', 'boosted_max_cp_range')
    op.create_table('boss_types',
    sa.Column('boss_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['boss_id'], ['bosses.id'], name='boss_types_boss_id_fkey'),
    sa.ForeignKeyConstraint(['type_id'], ['types.id'], name='boss_types_type_id_fkey')
    )
    op.create_table('bosses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('url_img', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('min_cp_range', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_cp_range', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('boosted_min_cp_range', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('boosted_max_cp_range', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='bosses_pkey'),
    sa.UniqueConstraint('name', name='bosses_name_key'),
    sa.UniqueConstraint('url_img', name='bosses_url_img_key')
    )
    op.drop_table('raid_pokemon_types')
    # ### end Alembic commands ###
