"""Add is_active to Raids

Revision ID: 88e1ab5126c4
Revises: 264f5e6be566
Create Date: 2021-09-09 12:07:33.190994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88e1ab5126c4'
down_revision = '264f5e6be566'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gyms', 'description',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.add_column('raids', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raids', 'is_active')
    op.alter_column('gyms', 'description',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###
