"""Edit boss_types model

Revision ID: 2d1cd4daf33d
Revises: 48ee7787dac4
Create Date: 2021-04-14 16:57:26.954136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d1cd4daf33d'
down_revision = '48ee7787dac4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boss_types', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boss_types', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
