"""Edit boss_types model

Revision ID: 48ee7787dac4
Revises: f0f2732e222d
Create Date: 2021-04-14 16:55:45.680533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48ee7787dac4'
down_revision = 'f0f2732e222d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boss_types', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boss_types', 'id')
    # ### end Alembic commands ###
