"""Create raids model

Revision ID: c7a5f1960770
Revises: dc3cdba1fb01
Create Date: 2021-04-14 14:36:39.757065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7a5f1960770'
down_revision = 'dc3cdba1fb01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('gym_id', sa.Integer(), nullable=False),
    sa.Column('boss_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['boss_id'], ['bosses.id'], ),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raids')
    # ### end Alembic commands ###
